version: "3.6"

services:
  library:
    container_name: ${PROJECT_NAME}_library
    image: openizr/node:3.0.0-dev
    env_file:
      - .env
    command: sh -c "
      dsync src/scripts/core.d.ts dist/core.d.ts &
      dsync src/scripts/plugins.d.ts dist/plugins.d.ts &
      dsync src/scripts/react.d.ts dist/react.d.ts &
      yarn && yarn run dev"
    volumes:
      - ./library:/var/www/html
    restart: unless-stopped
  playground:
    container_name: ${PROJECT_NAME}_playground
    image: openizr/node:3.0.0-dev
    env_file:
      - .env
    ports:
      - "${HOST_IP}:${PLAYGROUND_PORT}:${PLAYGROUND_PORT}"
    command: sh -c "dsync /library/dist/ node_modules/gincko/"
    volumes:
      - ./playground:/var/www/html
      - ./library:/library
    restart: unless-stopped

# For people that use a VPN
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.57.0/24
